### ISSUE TITLE
Matrix Builds Fail on Drone

### ISSUE THREAD

**Issue by firrae** [drone-plugins/drone-coverage#10]
Hey,

So after using this is a bit now I've found a couple things. One is an issue I think I caused where I'm using nyc to create the lcov file and for whatever reason aircover doesn't like it. But I did run into and issue with matrix builds in Drone. After the first build every proceeding build will fail with the message: `Cannot submit coverage. Cannot save build 1. meddler.Insert: DB error in Exec: UNIQUE constraint failed: builds.build_number, builds.build_repo_id`. While this isn't a big deal to me, it could be a game breaker for others.

**Comment by bradrydzewski** [comment]
yes, I should document this as a limitation. Aircover does not support multiple coverage reports for matrix builds. You can limit the coverage plugin to a single axis in the matrix using the when clause, similar to the following example:
http://readme.drone.io/usage/matrix/#deployments:4f8417ba6e069b3796db582fe0d5f9e1

**Comment by firrae** [comment]
OK, That looks good to me. I'll change my Drone file and see how it goes again. Will be nice knowing we have coverage across multiple versions of Node again 😄

**Comment by joshq00** [comment]
this also presents itself when re-running a build

builds that publish a coverage report **may never succeed more than once**. I feel this is a real problem.

Aircover doesn't necessarily need to change. Maybe the plugin can recognize this scenario and not 'exit 1'

**Comment by tboerger** [comment]
This plugin is not really actively maintained anymore, I gonna close that issue.
