### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ProLoser** [drone-plugins/drone-coverage#27]
This sucks: https://github.com/drone-plugins/drone-coverage/blob/master/DOCS.md

It's not even in the plugins list: http://plugins.drone.io/

**Comment by depado** [comment]
Any updates on this ? 😢

**Comment by tboerger** [comment]
This plugin is deprecated in the form like it is, it has been built for aircover, but aircover doesn't get any development. Maybe we will integrate some other tool at some point, but beside that Drone will get some integrated coverage reporting.

**Comment by depado** [comment]
Thanks for the update @tboerger !
Maybe it could be written somewhere in the README.md file so people don't get confused on why there is no documentation yet ? 
Also do you have any idea where I could follow the development of the integrated coverage reporting ? Any issue that is actively discussed in the drone repository ? I can't seem to find any information about this.

**Comment by tboerger** [comment]
> Maybe it could be written somewhere in the README.md file so people don't get confused on why there is no documentation yet ?

Yes maybe

> Also do you have any idea where I could follow the development of the integrated coverage reporting ? Any issue that is actively discussed in the drone repository ? I can't seem to find any information about this.

I have not checked the issues, but maybe you can find something on drone/drone. AFAIK it should be introduced with 0.9? For sure before 1.0.

**Comment by depado** [comment]
Thanks @tboerger I'll definitely check that out and maybe see if I can be of any help ☺

**Comment by mavimo** [comment]
@tboerger any possibility to see aircover FOSS?

**Comment by tboerger** [comment]
> @tboerger any possibility to see aircover FOSS?

It never had been opensourced.

**Comment by tboerger** [comment]
This plugin is not really actively maintained anymore, I gonna close that issue.
