### ISSUE TITLE
Is Aircover project dead?

### ISSUE THREAD

**Issue by mavimo** [drone-plugins/drone-coverage#29]
I see that aircover is not more available:

 - website is down: https://aircover.co/
 - github account seems removed: https://github.com/aircover/aircover

Project still existing or do you suggest to move to some other tool to have code coverage reports? This plugin will consider to add support to other tools then aircover?

**Comment by tboerger** [comment]
Drone will integrate coverage reports, but there are plugins available like https://github.com/robertstettner/drone-codecov

**Comment by tboerger** [comment]
This plugin is not really actively maintained anymore, I gonna close that issue.
