### ISSUE TITLE
Adding support for Elixir test coverage

### ISSUE THREAD

**Issue by marceldegraaf** [drone-plugins/drone-coverage#4]
I'm currently working on an Elixir/Phoenix project and would love to get coverage results into Aircover. However, there are currently no coverage tools for Elixir that support LCOV. The two most popular ones, however, output test coverage results to stdout, like so:

```
COV    FILE                                        LINES RELEVANT   MISSED
 75.0% lib/guru.ex                                    30        4        1
  0.0% lib/guru/endpoint.ex                           39        0        0
  0.0% lib/guru/repo.ex                                3        0        0
  0.0% test/support/channel_case.ex                   41        3        3
100.0% test/support/conn_case.ex                      42        3        0
...
100.0% web/views/shared_view.ex                       19        3        0
 50.0% web/views/status_helpers.ex                    14        2        1
  0.0% web/web.ex                                     83        1        1
[TOTAL]  44.9%
```

A simple regex would be enough to get the total test coverage for Aircover. Would you be interested in accepting a PR for such a generic "regex" output type?

**Comment by donny-dont** [comment]
@marceldegraaf to me it makes more sense to just extend the coverage tool you're using to output LCOV.

**Comment by tboerger** [comment]
This is currently nothing we will follow.
