### ISSUE TITLE
Aircover cannot find file in coverage report

### ISSUE THREAD

**Issue by marceldegraaf** [drone-plugins/drone-coverage#5]
I've set up Aircover on a Rails project, using `SimpleCov` and the `LcovFormatter`. Coverage reporting works: Aircover shows me the total coverage percentage and breakdowns per file:

![aircover 2016-02-19 13-06-53](https://cloud.githubusercontent.com/assets/15011/13175282/afb1ca16-d709-11e5-8d70-45801136b4c5.png)

However, when I click a file (e.g. `app/controllers/accounts_controller.rb`, the top one), Aircover shows an error:

![aircover 2016-02-19 13-08-18](https://cloud.githubusercontent.com/assets/15011/13175308/daa9103a-d709-11e5-8f9f-4d945627792e.png)

The output of the `coverage` plugin in the Drone build does show that file, though:

`Parsing coverage file /drone/src/git.yourkarma-private.com/code/login/coverage/lcov/app-controllers-accounts_controller.rb.lcov`

Am I missing something, or is this a bug?

**Comment by donny-dont** [comment]
Does it show any files? The `./` at the start looks a bit sketchy.

**Comment by bradrydzewski** [comment]
at first glance, my guess is that the lcov file is incorrectly formatted. Per the lcov spec [1] it should use absolute file paths and not relative file paths.

> For  each  source  file  referenced in the .da file, there is a section containing filename and coverage data:
> SF:[absolute path to the source file]

[1] http://ltp.sourceforge.net/coverage/lcov/geninfo.1.php

**Comment by marceldegraaf** [comment]
@bradrydzewski thanks, looks like that's the problem. There's an issue for this on the `simplecov-lcov` tracker, so hopefully that's fixed soon.

**Comment by marceldegraaf** [comment]
Yep, using [this fork](https://github.com/Bugagazavr/simplecov-lcov) of the LCOV formatter fixes the paths. (it belongs to [this PR](https://github.com/fortissimo1997/simplecov-lcov/pull/18) in the LCOV formatter plugin's repo)

@bradrydzewski another question: is there supposed to be color coding for hits/misses in the individual files? Because now I can open a file in Aircover, but all lines are light gray-ish without any indication of actual test coverage per line.

**Comment by tboerger** [comment]
> @bradrydzewski another question: is there supposed to be color coding for hits/misses in the individual files? Because now I can open a file in Aircover, but all lines are light gray-ish without any indication of actual test coverage per line.

As you can see on https://aircover.co/drone-plugins/drone-git/53/main.go it should be colored if it got some coverage.

**Comment by marceldegraaf** [comment]
Hm, weird. Even a file with 100% coverage doesn't have any colored lines; they're all gray. What's the best place to start if I want to debug this?

**Comment by tboerger** [comment]
I think the best start is to compare the generated lcov file with the lcov standard :D

**Comment by marceldegraaf** [comment]
Right, so when I pull the generated LCOV file through `genhtml`, it correctly generates coverage information for these files. Interestingly enough, that even happens with the non-absolute file paths (starting with `./`)

This is an excerpt of the generated LCOV file that parses correctly in `genhtml`:

```
SF:./app/controllers/application_controller.rb
DA:1,1
DA:2,1
DA:4,1
DA:6,1
DA:8,1
DA:9,9
DA:10,9
DA:13,1
DA:14,0
DA:15,0
DA:16,0
DA:19,1
DA:20,14
DA:21,14
DA:22,4
DA:24,10
DA:28,1
DA:29,10
DA:30,8
DA:32,2
DA:39,1
DA:40,9
DA:41,9
DA:44,1
DA:45,5
DA:48,1
DA:49,1
DA:50,0
end_of_record
SF:./app/controllers/me_controller.rb
DA:1,1
DA:2,1
DA:4,1
DA:5,2
DA:6,1
DA:7,1
DA:16,1
end_of_record
...
```

**Comment by bradrydzewski** [comment]
The recommended fix right now is to use `sed` to alter the path in the file before the coverage plugin executes. To account for relative paths the plugin will need to be refactored and updated accordingly. This isn't something I'm planning in the short term (I'm focused on drone 0.5) but am open to pull requests here. If anyone is interested reach out in the [gitter room](https://gitter.im/drone/drone)
